version: '3.9'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: andrea
      POSTGRES_PASSWORD: AndreaSimone2023
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
