// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.543
package templates

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

import "github.com/andreabertanzon/simtek/data"

func Index(date string, interventions []data.Intervention) templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<html><head><title>Go app super</title><link href=\"/css/output.css\" rel=\"stylesheet\" type=\"text/css\"><style>\n\t\t\t\tdiv.htmx-swapping {\n\t\t\t\t\topacity: 0;\n\t\t\t\t\ttransition: opacity 1s ease-out;\n\t\t\t\t}\n\n\t\t\t\tdiv.htmx-revealing {\n\t\t\t\t\topacity: 0;\n\t\t\t\t\ttransition: opacity 1s ease-in;\n\t\t\t\t}\n\n\t\t\t\tdiv#main-content {\n\t\t\t\t\tpadding-left: 1rem; /* Adjust as needed */\n\t\t\t\t\tpadding-right: 1rem; /* Adjust as needed */\n\t\t\t\t}\n\t\t\t</style></head><body id=\"body\" class=\"h-screen\"><div id=\"main-content\" class=\"h-screen w-screen p-2 flex flex-col items-center\"><div id=\"action-container\" class=\"flex mt-8 px-8 cursor-pointer\" hx-get=\"/new-intervention\" hx-target=\"#intervention-content\" hx-trigger=\"click, keyup[ctrlKey&amp;&amp;key==&#39;/&#39;] from:body\" hx-swap=\"innerHTML swap:200ms\"><p id=\"date\" class=\"text-6xl mr-2\" hx-get=\"/select-date\" hx-target=\"#date\" hx-swap=\"outerHTML\">Oggi: ")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var2 string
		templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.JoinStringErrs(date)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `templates/index.templ`, Line: 42, Col: 18}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var2))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</p><svg class=\"cursor-pointer\" width=\"48\" height=\"48\" xmlns=\"http://www.w3.org/2000/svg\" fill-rule=\"evenodd\" clip-rule=\"evenodd\"><path d=\"M12 0c-6.627 0-12 5.373-12 12s5.373 12 12 12 12-5.373 12-12-5.373-12-12-12zm7 14h-5v5h-4v-5h-5v-4h5v-5h4v5h5v4z\"></path></svg></div><div id=\"intervention-content\" class=\"p-4 mb-4 overflow-auto mt-4 w-full h-auto\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = InterventionContainer(interventions).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</div></div><script src=\"https://unpkg.com/htmx.org\"></script></body></html>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}
