// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.639
package templates

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

import "github.com/andreabertanzon/simtek/data"

func IndexCopy(date string, interventions []data.Intervention) templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<html><head><title>Go app super</title><link href=\"/css/output.css\" rel=\"stylesheet\" type=\"text/css\"><style>\n\t\t\t\tdiv.htmx-swapping {\n\t\t\t\t\topacity: 0;\n\t\t\t\t\ttransition: opacity 1s ease-out;\n\t\t\t\t}\n\n\t\t\t\tdiv.htmx-revealing {\n\t\t\t\t\topacity: 0;\n\t\t\t\t\ttransition: opacity 1s ease-in;\n\t\t\t\t}\n\n\t\t\t\tdiv#main-content {\n\t\t\t\t\tpadding-left: 1rem; /* Adjust as needed */\n\t\t\t\t\tpadding-right: 1rem; /* Adjust as needed */\n\t\t\t\t}\n\t\t\t</style></head><body class=\"h-screen\"><div id=\"main-content\" class=\"w-screen p-2 flex flex-col items-center gap-4\"><div id=\"action-container\" class=\"w-full items-center p-2\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = DateInput(date).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</div><div id=\"intervention-content\" class=\"p-4 mb-4 overflow-auto mt-4 w-full h-auto\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = InterventionContainer(interventions).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</div></div><script src=\"https://unpkg.com/htmx.org\"></script></body></html>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}
